/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjForm;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Matúš
 */
public class Change_Password_Form extends javax.swing.JFrame {

    /**
     * Creates new form Change_Password_Form
     */
    
    String login_email;
    String login_name;
    
    public Change_Password_Form() {
        initComponents();
        
        this.setLocationRelativeTo(null);        // Form will be showed in center of screen
    }
    
    public Change_Password_Form(String login_name, String login_email)
    {
        initComponents();
        
        this.setLocationRelativeTo(null);        // Form will be showed in center of screen
        this.login_name = login_name;
        this.login_email = login_email;   
    }
    
    public boolean Check_Inputs()
    {
        if(input_new_password.getText().equals("") || input_confirm_password.getText().equals(""))
        {
            return false;
        }
        
        else
        {
            return true;
        }
    }
    
    public void Clean_Input_Fields()
    {
        input_new_password.setText("");
        input_confirm_password.setText("");
    }
    
    
    
    
    
    
    public boolean Verify_New_Password_Match()
    {
        if(input_new_password.getText().equals(input_confirm_password.getText()))       // if new password and confirmation are the same
        {
                // execute UPDATE in Table
                
                
                
                
                return true;
        }
            
        else
        {
            JOptionPane.showMessageDialog(null, "New password and Confirm password must be the same, Try again!!!");
            Clean_Input_Fields();
            
            return false;
        }
    }
    
    
    public void Update_Password()
    {
        if(Verify_New_Password_Match())     // if password confirmation is corrected
        {
            Connection_Class c = new Connection_Class(); 
            Connection con = c.getConnection();
        
            try {
                //"UPDATE products SET name = ?, price = ?, add_date = ?, image = ? WHERE id = ?";
                PreparedStatement ps = con.prepareStatement ("UPDATE registered_users SET name = ?, password = ? ,confirm_password = ? WHERE email = ?");
                ps.setString(1, this.login_name);
               
                ps.setString(2, input_new_password.getText());
                ps.setString(3, input_confirm_password.getText());
                 ps.setString(4, this.login_email);  
                
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Done"); 
            
            } catch (SQLException ex) {
                Logger.getLogger(Change_Password_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else
        {
            // Verify_New_Password_Match will caused false and show message for user
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_confirm_password = new javax.swing.JPasswordField();
        input_new_password = new javax.swing.JPasswordField();
        send_new_password_button = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/change password.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 58, -1, -1));

        jLabel2.setText("New password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 240, -1, -1));

        jLabel3.setText("Confirm password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 314, -1, -1));
        getContentPane().add(input_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 307, 409, 31));
        getContentPane().add(input_new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 233, 409, 31));

        send_new_password_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/next send.png"))); // NOI18N
        send_new_password_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                send_new_password_buttonMouseMoved(evt);
            }
        });
        send_new_password_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send_new_password_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(send_new_password_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 391, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_new_password_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_new_password_buttonMouseClicked
        
        if(!(Check_Inputs()))       // if you did not entered all input fields
        {
            JOptionPane.showMessageDialog(null, "Please, enter all input fiels!!!");
            Clean_Input_Fields(); 
        }
        
        else    // input fields will be verified 
        {
            Update_Password();
        }
    }//GEN-LAST:event_send_new_password_buttonMouseClicked

    private void send_new_password_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_new_password_buttonMouseMoved

        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        send_new_password_button.setCursor(c); 
    }//GEN-LAST:event_send_new_password_buttonMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Password_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField input_confirm_password;
    private javax.swing.JPasswordField input_new_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel send_new_password_button;
    // End of variables declaration//GEN-END:variables
}
