/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjForm;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Matúš
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    
    public String name_login_user;
    public String email_login_user;
    
    public Object connection_check = null;
    
    
    public Login_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Connection_Class c = new Connection_Class();
         
        connection_check = c.getConnection();
        Check_connection();
    }
    
    public boolean Check_connection()
    {
        
        
        if(connection_check != null) 
        {
                    ImageIcon originalIcon = new ImageIcon("ok.png");
                   
                   connection_label.setIcon(originalIcon);
                   return true;
        }
        
        else
        {
                   ImageIcon originalIcon = new ImageIcon("not_ok.png");
                   
                   connection_label.setIcon(originalIcon);
                   return false;
        }
    }
    
    

    public boolean Check_Inputs()
    {
        String blank_string = "";
        
       if(blank_string.equals(login_input_one.getText()) || blank_string.equals(login_input_two.getText()))
        {
            return false;
        }

        else
        {
            try
            {

               return true;
            } catch(Exception ex)                       // another change
            {
                return false;
            }
        }
    }
    
    public void Clean_Input_Fields()
    {
        login_input_one.setText("");
        login_input_two.setText("");  
    }


    public boolean Check_Existing_Records() throws SQLException
    {
        boolean return_match = true;
        String query = "SELECT * FROM registered_users"; 

        Connection_Class c = new Connection_Class();
        Connection con = c.getConnection();

        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(query);

        while(rs.next())
        {

            name_login_user = rs.getString("name");
            email_login_user = rs.getString("email");
            String Password = rs.getString("password");

           // System.out.println("Value of first string: "+reg_input_one.getText());
           // System.out.println("Value of Name from table: "+Name);
           
          
           

            if(email_login_user.equals(login_input_one.getText()))  
            {
                return_match = true;
                break;
            }

            else
            {
                return_match = false;
            }



        }


        return return_match;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ok_login_button = new javax.swing.JButton();
        login_input_two = new javax.swing.JPasswordField();
        login_input_one = new javax.swing.JTextField();
        arrow_back = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        connection_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/title_login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 45, -1, -1));

        jLabel2.setText("E-mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 213, -1, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 296, -1, -1));

        ok_login_button.setBackground(new java.awt.Color(255, 255, 255));
        ok_login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/ok_button.png"))); // NOI18N
        ok_login_button.setText("OK");
        ok_login_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ok_login_buttonMouseMoved(evt);
            }
        });
        ok_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(ok_login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 373, -1, -1));

        login_input_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_input_twoActionPerformed(evt);
            }
        });
        getContentPane().add(login_input_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 284, 389, 40));

        login_input_one.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_input_one.setPreferredSize(new java.awt.Dimension(59, 50));
        login_input_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_input_oneActionPerformed(evt);
            }
        });
        getContentPane().add(login_input_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 201, 389, 40));

        arrow_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/arrow_back.png"))); // NOI18N
        arrow_back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                arrow_backMouseMoved(evt);
            }
        });
        arrow_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrow_backMouseClicked(evt);
            }
        });
        getContentPane().add(arrow_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 364, -1, -1));

        jLabel6.setText("Connection with database: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));
        getContentPane().add(connection_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 62, 63));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_login_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_login_buttonMouseMoved
        // TODO add your handling code here:


        Cursor c = new Cursor(Cursor.HAND_CURSOR); 
        ok_login_button.setCursor(c);
    }//GEN-LAST:event_ok_login_buttonMouseMoved

    private void login_input_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_input_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_input_twoActionPerformed

    private void ok_login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_login_buttonActionPerformed

        try {
            System.out.println("Check input: "+Check_Inputs());
            System.out.println("Check login: "+Check_Existing_Records()); 
            
            if(Check_Inputs())          // Email and Password are entered
            {
                
                try {
                    if(Check_Existing_Records())       // Match with other records of table
                    {
                        JOptionPane.showMessageDialog(null, "Login successful!!!");           // when record was added sucesfully, showbox will appear
                        setVisible(false);                          // Start Form will disapear
                       
                        
                        Profile f = new Profile(name_login_user, email_login_user);
                        f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-email.png")));
                        f.setVisible(true);
                        
                        //new Profile(name_login_user,email_login_user).setVisible(true);        
                        
                    }
                    
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Email or Password is Incorrect!!!");           // when record was added sucesfully, showbox will appear
                        Clean_Input_Fields();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Enter all input fields!!!");
                Clean_Input_Fields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }





    }//GEN-LAST:event_ok_login_buttonActionPerformed

    private void login_input_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_input_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_input_oneActionPerformed

    private void arrow_backMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_backMouseMoved

        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        arrow_back.setCursor(c);

    }//GEN-LAST:event_arrow_backMouseMoved

    private void arrow_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_backMouseClicked
        // TODO add your handling code here:

        setVisible(false);                          // Start Form will disapear

        Start_Form f = new Start_Form();      // Register Form will be showed
        f.setVisible(true);
    }//GEN-LAST:event_arrow_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow_back;
    private javax.swing.JLabel connection_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField login_input_one;
    private javax.swing.JPasswordField login_input_two;
    private javax.swing.JButton ok_login_button;
    // End of variables declaration//GEN-END:variables
}
