/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjForm;

import java.awt.Cursor;
import java.awt.Toolkit;

/**
 *
 * @author Matúš
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
  
    
    public Profile() {
        initComponents();
        this.setLocationRelativeTo(null);        // Form will be showed in center of screen
    }
    
    public Profile(String name_login_user, String email_login_user) 
    {
        initComponents();
        this.setLocationRelativeTo(null);        // Form will be showed in center of screen
        
        
        
        
        login_user_name.setText(name_login_user);
        login_user_email.setText(email_login_user);
        
        login_user_name.setEditable(false);                                   // inputField with email will be read-only 
        login_user_email.setEditable(false);
        
    
        
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        send_email_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        change_password_button = new javax.swing.JButton();
        log_out_button = new javax.swing.JButton();
        login_user_email = new javax.swing.JTextField();
        login_user_name = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/profile.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 65, -1, -1));

        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 341, -1, -1));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 274, -1, 27));

        send_email_button.setText("Send E-mail");
        send_email_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                send_email_buttonMouseMoved(evt);
            }
        });
        send_email_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send_email_buttonMouseClicked(evt);
            }
        });
        send_email_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_email_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(send_email_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 198, 132, -1));

        jLabel6.setText("Last login ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 398, -1, -1));

        change_password_button.setText("Change password");
        change_password_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                change_password_buttonMouseMoved(evt);
            }
        });
        change_password_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_password_buttonMouseClicked(evt);
            }
        });
        change_password_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_password_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(change_password_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 198, -1, -1));

        log_out_button.setText("Log out");
        log_out_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                log_out_buttonMouseMoved(evt);
            }
        });
        log_out_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_out_buttonMouseClicked(evt);
            }
        });
        log_out_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(log_out_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 198, 132, -1));
        getContentPane().add(login_user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 338, 304, -1));
        getContentPane().add(login_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 276, 304, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 395, 304, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_email_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_email_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_email_buttonActionPerformed

    private void change_password_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_password_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change_password_buttonActionPerformed

    private void log_out_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_log_out_buttonActionPerformed

    private void change_password_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_password_buttonMouseMoved
        // TODO add your handling code here:
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        change_password_button.setCursor(c); 
    }//GEN-LAST:event_change_password_buttonMouseMoved

    private void send_email_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_email_buttonMouseMoved
        // TODO add your handling code here:
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        send_email_button.setCursor(c); 
    }//GEN-LAST:event_send_email_buttonMouseMoved

    private void log_out_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_buttonMouseMoved
        // TODO add your handling code here:
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        log_out_button.setCursor(c); 
    }//GEN-LAST:event_log_out_buttonMouseMoved

    private void send_email_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_email_buttonMouseClicked
        // TODO add your handling code here:
        
        setVisible(false);         
        
        Send_Email f = new Send_Email(login_user_email.getText());
        f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-email.png")));
        f.setVisible(true);
                                          
        
    }//GEN-LAST:event_send_email_buttonMouseClicked

    private void log_out_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_buttonMouseClicked

        setVisible(false);         
        
        Start_Form f = new Start_Form();
      //  f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-email.png")));
        f.setVisible(true);
        
    }//GEN-LAST:event_log_out_buttonMouseClicked

    private void change_password_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_password_buttonMouseClicked

        setVisible(false);                          // Start Form will disapear
        Change_Password_Form f = new Change_Password_Form(login_user_name.getText(), login_user_email.getText());      // Register Form will be showed
      
        f.setVisible(true);       
    }//GEN-LAST:event_change_password_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_password_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton log_out_button;
    private javax.swing.JTextField login_user_email;
    private javax.swing.JTextField login_user_name;
    private javax.swing.JButton send_email_button;
    // End of variables declaration//GEN-END:variables
}
