/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjForm;
 
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Matúš
 */
public class Register_Form extends javax.swing.JFrame {  

    /**
     * Creates new form Register_Form
     */
   
    public Object connection_check = null;
    
    
    
    public Register_Form() {
        initComponents();
        
        
             
        this.setLocationRelativeTo(null);              // Form will be showed in center of screen
        
        Connection_Class c = new Connection_Class();
       
        connection_check = c.getConnection();
        Check_connection(connection_check);
        
        
        // pozriec connection  connection_check
        
        // potom dat vlastnu funkciu cez classu ktora sa zavola, Class_Draw_Icon c = new Class_Draw_Icon();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public boolean Check_connection(Object check) 
    {
        System.out.println("Check connection: "+check);
        
        if(check != null) 
        {
                    ImageIcon originalIcon = new ImageIcon("ok.png");
                   
                   connection_label_reg_form.setIcon(originalIcon);
                   return true;
        }
        
        else
        {
                   ImageIcon originalIcon = new ImageIcon("not_ok.png");
                   
                   connection_label_reg_form.setIcon(originalIcon);
                   return false ;
        }
    }
    
    
    
    
    public boolean Check_Inputs()
    {
        
        if(reg_input_one.getText().equals("") || reg_input_two.getText().equals("") || reg_input_three.getText().equals("") || reg_input_four.getText().equals(""))
        {
            return false;
        }
        
        else
        {
            return true;
        }
    }
    
    public void Clean_Input_Fields()
    {
        reg_input_one.setText("");
        reg_input_two.setText("");
        reg_input_three.setText("");
        reg_input_four.setText("");    
    }
    
    public boolean Check_Existing_Records() throws SQLException
    {
        boolean return_match = true;
        String query = "SELECT * FROM registered_users";
        
        Connection_Class c = new Connection_Class();
        Connection con = c.getConnection();
        
        Statement st = con.createStatement();
        
        ResultSet rs = st.executeQuery(query); 
        
        // skus toto 
        
       //ResultSet count = st.executeQuery("SELECT COUNT(*) FROM registered_users");
        
       
        
        // uvidis
        
        // problem, ak je jeden zaznam
        
        while(rs.next())                    // if table has more than 
        {
            
            String Name = rs.getString("name");
            String Email = rs.getString("email");
            String Password = rs.getString("password");
            String Con_Password = rs.getString("confirm_password");
            
        //    System.out.println("Value of first string: "+reg_input_one.getText());
       //     System.out.println("Value of Name from table: "+Name);
            
            
            if(reg_input_two.getText().equals(Email)) 
            {
                return_match = true; 
                break;
            }
            
            else
            {
                return_match = false;
            }
            
            
        }
        
        
        return return_match; 
    }
    
    
    
    
    
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        send_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        reg_input_two = new javax.swing.JTextField();
        reg_input_one = new javax.swing.JTextField();
        reg_input_three = new javax.swing.JPasswordField();
        reg_input_four = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        arrow_back = new javax.swing.JLabel();
        connection_label_reg_form = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Registration_title.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 43, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 178, -1, -1));

        jLabel3.setText("E-mail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 254, -1, -1));

        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 325, -1, -1));

        jLabel5.setText("Confirm password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 404, -1, -1));

        send_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/next send.png"))); // NOI18N
        send_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                send_buttonMouseMoved(evt);
            }
        });
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(send_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        jLabel6.setText("Connection with database: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, -1, -1));

        reg_input_two.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg_input_two.setPreferredSize(new java.awt.Dimension(59, 50));
        reg_input_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_input_twoActionPerformed(evt);
            }
        });
        getContentPane().add(reg_input_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 242, 380, 40));

        reg_input_one.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg_input_one.setPreferredSize(new java.awt.Dimension(59, 50));
        reg_input_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_input_oneActionPerformed(evt);
            }
        });
        getContentPane().add(reg_input_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 166, 380, 40));

        reg_input_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_input_threeActionPerformed(evt);
            }
        });
        getContentPane().add(reg_input_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 312, 380, 43));

        reg_input_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_input_fourActionPerformed(evt);
            }
        });
        getContentPane().add(reg_input_four, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 391, 380, 43));

        jLabel7.setText("* name and password must be the same with your Gmail account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 132, -1, -1));

        arrow_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/arrow_back.png"))); // NOI18N
        arrow_back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                arrow_backMouseMoved(evt);
            }
        });
        arrow_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrow_backMouseClicked(evt);
            }
        });
        getContentPane().add(arrow_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));
        getContentPane().add(connection_label_reg_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 62, 63));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        jLabel8.setText("jLabel2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        try {
            // TODO add your handling code here:
                System.out.println("Check inputs: "+Check_Inputs());
                System.out.println("Existing record: "+Check_Existing_Records()); 
           
                
               
                
                
                if(Check_Inputs() && reg_input_three.getText().equals(reg_input_four.getText()))
                {
                    Connection_Class c = new Connection_Class();
                
                    Connection con = c.getConnection();   
                    
                    int get_result = 0;     // default initializaton before adjusting
                    
                    if(reg_input_two.getText().contains("@gmail.com"))
                    { 
                        if(Check_Existing_Records())
                        {
                            get_result = 1;
                        }
                    
                        else
                        {
                            get_result = 0;
                        }
                    }
                    
                    
                    else
                    {
                        get_result = 2;     // means, that email does not inlucde "@gmail.com" substring
                        
                        
                    }
                    
                
                
                try
                {
                    switch(get_result)
                    {
                        case 0: 
                                        PreparedStatement ps = con.prepareStatement("INSERT INTO registered_users(name,email,password,confirm_password)"
                                        + "values(?,?,?,?) ");
                                        ps.setString(1, reg_input_one.getText());
                                        ps.setString(2, reg_input_two.getText());
                                        ps.setString(3, reg_input_three.getText());
                                        ps.setString(4, reg_input_four.getText());
                    
                                        System.out.println("heslo: "+reg_input_three.getText());
                                        System.out.println("overenie hesla: "+reg_input_four.getText());
                    
                                        ps.executeUpdate();
                                        
                                        JOptionPane.showMessageDialog(null, "Data was added sucesfully");           // when record was added sucesfully, showbox will appear
                    
                                        setVisible(false);                          // Start Form will disapear
                    
                                        Start_Form s = new Start_Form();      // Register Form will be showed
                                        s.setVisible(true);
                        
                        break;
                        
                        case 1 :         JOptionPane.showMessageDialog(null, "Record already exists");
                                        Clean_Input_Fields();
                                      
                        break;
                        
                        case 2 : JOptionPane.showMessageDialog(null, "Your email must include '@gmail.com' ending characters"); Clean_Input_Fields(); break;
                    }
                    }
                
                    catch(Exception ex)
                    {
                        Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }
          
            
            else
            {
                JOptionPane.showMessageDialog(null,"Please enter all text fields, or Password confirmation was not same!!!");
                Clean_Input_Fields();
                
            }
       
                    
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_send_buttonActionPerformed

    private void reg_input_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_input_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_input_twoActionPerformed

    private void reg_input_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_input_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_input_oneActionPerformed

    private void reg_input_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_input_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_input_threeActionPerformed

    private void reg_input_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_input_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_input_fourActionPerformed

    private void arrow_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_backMouseClicked
        // TODO add your handling code here:
        
        setVisible(false);                          // Start Form will disapear
        
        Start_Form f = new Start_Form();      // Register Form will be showed
        f.setVisible(true);  
    }//GEN-LAST:event_arrow_backMouseClicked

    private void arrow_backMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_backMouseMoved
     
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        arrow_back.setCursor(c); 
        
        
    }//GEN-LAST:event_arrow_backMouseMoved

    private void send_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_buttonMouseMoved
       
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        send_button.setCursor(c); 
    }//GEN-LAST:event_send_buttonMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow_back;
    private javax.swing.JLabel connection_label_reg_form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField reg_input_four;
    private javax.swing.JTextField reg_input_one;
    private javax.swing.JPasswordField reg_input_three;
    private javax.swing.JTextField reg_input_two;
    private javax.swing.JButton send_button;
    // End of variables declaration//GEN-END:variables
}
