/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjForm;

import java.awt.Cursor;
import java.util.Date;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.rmi.transport.Transport;

/**
 *
 * @author Matúš
 */
public class Send_Email extends javax.swing.JFrame {  

    /**
     * Creates new form Send_Email
     */
    public Object connection_check = null;
    
    public Send_Email() {
        initComponents(); 
        this.setLocationRelativeTo(null);
    }
    
    public Send_Email(String para)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Connection_Class c = new Connection_Class();
       
        connection_check = c.getConnection();
        Check_connection(connection_check);
        
        send_email_input_from.setText(para);
        send_email_input_from.setEditable(false);                                   // inputField with email will be read-only 
        
    }
    
    
    public boolean Check_connection(Object check)
    {
        
        
        if(check != null) 
        {
                    ImageIcon originalIcon = new ImageIcon("ok.png");
                   
                   connection_label.setIcon(originalIcon);
                   return true;
        }
        
        else
        {
                   ImageIcon originalIcon = new ImageIcon("not_ok.png");
                   
                   connection_label.setIcon(originalIcon);
                   return false;
        }
    }
    
    public boolean please_Check_my_Inputs()
    {
        
        if(send_email_input_to.getText().equals("") || send_email_input_subject.getText().equals("") || send_email_input_message.getText().equals(""))
        {
            return false;
        }
        
        else
        {
            return true;
        }
    }
    
    public void Clean_Input_Fields()
    {
        
        send_email_input_to.setText("");
        send_email_input_subject.setText("");
        send_email_input_message.setText("");    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrow_back = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        send_email_input_to = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        send_email_input_from = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        send_email_input_subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        send_email_input_message = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        send_email_button = new javax.swing.JButton();
        arrow_back_to_profile = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        connection_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        arrow_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/arrow_back.png"))); // NOI18N
        arrow_back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                arrow_backMouseMoved(evt);
            }
        });
        arrow_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrow_backMouseClicked(evt);
            }
        });

        jLabel6.setText("Connection with database: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Send_Email_title.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 34, -1, -1));

        send_email_input_to.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        send_email_input_to.setPreferredSize(new java.awt.Dimension(59, 50));
        send_email_input_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_email_input_toActionPerformed(evt);
            }
        });
        getContentPane().add(send_email_input_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 536, 40));

        jLabel2.setText("Consignor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        send_email_input_from.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        send_email_input_from.setPreferredSize(new java.awt.Dimension(59, 50));
        send_email_input_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_email_input_fromActionPerformed(evt);
            }
        });
        getContentPane().add(send_email_input_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 536, 40));

        jLabel3.setText("Recipient");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel4.setText("Subject");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        send_email_input_subject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        send_email_input_subject.setPreferredSize(new java.awt.Dimension(59, 50));
        send_email_input_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_email_input_subjectActionPerformed(evt);
            }
        });
        getContentPane().add(send_email_input_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 536, 40));

        send_email_input_message.setColumns(20);
        send_email_input_message.setRows(5);
        jScrollPane1.setViewportView(send_email_input_message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 536, -1));

        jLabel5.setText("Message");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        send_email_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/next send.png"))); // NOI18N
        send_email_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                send_email_buttonMouseMoved(evt);
            }
        });
        send_email_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send_email_buttonMouseClicked(evt);
            }
        });
        send_email_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_email_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(send_email_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 456, -1, -1));

        arrow_back_to_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/arrow_back.png"))); // NOI18N
        arrow_back_to_profile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                arrow_back_to_profileMouseMoved(evt);
            }
        });
        arrow_back_to_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrow_back_to_profileMouseClicked(evt);
            }
        });
        getContentPane().add(arrow_back_to_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel8.setText("Connection with database: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));
        getContentPane().add(connection_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 62, 63));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        jLabel10.setText("jLabel2");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_email_input_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_email_input_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_email_input_toActionPerformed

    private void send_email_input_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_email_input_fromActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_send_email_input_fromActionPerformed

    private void send_email_input_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_email_input_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_email_input_subjectActionPerformed

    private void send_email_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_email_buttonActionPerformed

         
     
    }//GEN-LAST:event_send_email_buttonActionPerformed

    private void arrow_backMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_backMouseMoved

        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        arrow_back.setCursor(c);

    }//GEN-LAST:event_arrow_backMouseMoved

    private void arrow_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_backMouseClicked
        // TODO add your handling code here:

        setVisible(false);                          // Start Form will disapear

        Start_Form f = new Start_Form();      // Register Form will be showed
        f.setVisible(true);
    }//GEN-LAST:event_arrow_backMouseClicked

    private void arrow_back_to_profileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_back_to_profileMouseMoved

        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        arrow_back_to_profile.setCursor(c);

    }//GEN-LAST:event_arrow_back_to_profileMouseMoved

    private void arrow_back_to_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrow_back_to_profileMouseClicked
        // TODO add your handling code here:

        setVisible(false);                          // Start Form will disapear

        Profile f = new Profile();      // Register Form will be showed
        f.setVisible(true);
    }//GEN-LAST:event_arrow_back_to_profileMouseClicked

    private void send_email_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_email_buttonMouseClicked
        // TODO add your handling code here:
        
        System.out.println("Check Inputs: "+please_Check_my_Inputs()); 
        if((please_Check_my_Inputs() == true))
        {
            Email e = new Email();
            e.sendEmail(send_email_input_from.getText(), send_email_input_to.getText(),send_email_input_subject.getText(), send_email_input_message.getText());
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Fill all input fields, please!!!");
            Clean_Input_Fields();
        }
                 
    }//GEN-LAST:event_send_email_buttonMouseClicked

    private void send_email_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_email_buttonMouseMoved
 
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        send_email_button.setCursor(c);

    }//GEN-LAST:event_send_email_buttonMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Send_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Send_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Send_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Send_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Send_Email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow_back;
    private javax.swing.JLabel arrow_back_to_profile;
    private javax.swing.JLabel connection_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send_email_button;
    private javax.swing.JTextField send_email_input_from;
    private javax.swing.JTextArea send_email_input_message;
    private javax.swing.JTextField send_email_input_subject;
    private javax.swing.JTextField send_email_input_to;
    // End of variables declaration//GEN-END:variables
}
